version: '3.8'

networks:
  backend:
    driver: bridge

services:
  switchermanagement:
    image: trackerforce/switcher-management:latest
    container_name: switchermanagement
    # Enable SSL with "./setup.sh true"
    command: ["/bin/sh", "-c", "./setup.sh true"]
    ports:
      - 443:443
      - 80:80
    volumes: 
      - /data/certs:/etc/nginx/conf.d
    networks:
      - backend
    environment: 
      - SWITCHERAPI_URL=https://switcherapi.com/api
      - SM_IP=localhost
      # - GOOGLE_RECAPTCHA=
      # - ALLOW_INTERNAL_AUTH=
      # - GITHUB_CLIENTID=
      # - BITBUCKET_CLIENTID=
      # - SWITCHERSLACKAPP_URL=[ENDPOINT]/slack/install