version: '3.8'

networks:
  backend:
    driver: bridge

services:
  switchermanagement:
    image: trackerforce/switcher-management
    container_name: switchermanagement
    command: /bin/sh -c "setup.sh"
    ports:
      - 80:80
    networks:
      - backend
    environment: 
      - SWITCHERAPI_URL=https://switcher-api.herokuapp.com
      - SM_IP=localhost
      # - GOOGLE_RECAPTCHA=6LcpJ74ZAAAAAGY88BXVyk1qwjPhb2PmKXeoh5yT
      # - GITHUB_CLIENTID=5745650fe81a1f1f3486
      # - BITBUCKET_CLIENTID=JNfFteJqcjcDytFAh5
      # - SWITCHERSLACKAPP_URL=https://switcher-slack-app.herokuapp.com/slack/install