version: '3.8'

networks:
  backend:
    driver: bridge

services:
  switchermanagement:
    image: trackerforce/switcher-management
    container_name: switchermanagement
    command: /bin/sh -c "setup.sh"
    ports:
      - 80:80
    networks:
      - backend
    environment: 
      - SWITCHERAPI_URL=https://switcherapi.com/api
      - SM_IP=localhost
      # - GOOGLE_RECAPTCHA=
      # - ALLOW_INTERNAL_AUTH=
      # - GITHUB_CLIENTID=
      # - BITBUCKET_CLIENTID=
      # - SWITCHERSLACKAPP_URL=[ENDPOINT]/slack/install