version: '3.9'

services:

  switchermanagement:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: switcher-api

  switcherapi:
    image: trackerforce/switcher-api:latest
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - ENV=dev

      - MONGODB_URI=mongodb://mongodb:27017/switcher-api
      - RESOURCE_SECRET=admin
      - JWT_SECRET=admin
      - JWT_ADMIN_TOKEN_RENEW_INTERVAL=10m
      - MAX_STRATEGY_OPERATION=100
      - RELAY_BYPASS_HTTPS=true
      - RELAY_BYPASS_VERIFICATION=true
      - HISTORY_ACTIVATED=true
      - METRICS_MAX_PAGE=50
      - MAX_REQUEST_PER_MINUTE=0
      - GOOGLE_SKIP_AUTH=true
      
      - SWITCHER_API_LOGGER=true
      - SWITCHER_API_ENABLE=false
      - SWITCHER_API_URL=http://localhost:3000
      - SWITCHER_API_KEY=[SWITCHER_API_KEY]
      - SWITCHER_API_DOMAIN="Switcher API"
      - SWITCHER_API_ENVIRONMENT="default"
    depends_on:
      - mongodb